const gameAchievements = [
    {
        id: 'main_first_click',
        name: 'はじめてのクリック',
        description: '記念すべき最初の一杯。ここから全てが始まる。',
        icon: '👆',
        condition: { type: 'clicks', value: 1 },
        fame: 1,
        type: 'main',
    },
    {
        id: 'main_make_100',
        name: '甘い一歩',
        description: 'アイス作りも、百個から。',
        icon: '🍨',
        condition: { type: 'totalIceCreams', value: 100 },
        fame: 1,
        type: 'main',
    },
    {
        id: 'main_buy_grandpa',
        name: 'おじいちゃん、よろしく！',
        description: '全ての始まり。おじいちゃんが作るアイスは、なぜか少し懐かしい味がする。',
        icon: '👴',
        condition: { type: 'specificBuildingCount', id: 'grandpa', value: 1 },
        fame: 1,
        type: 'main',
    },
    {
        id: 'main_ips_1',
        name: '小さな自動化',
        description: '放置していても、アイスは増える。素晴らしい世界の幕開けだ。',
        icon: '⚙️',
        condition: { type: 'ips', value: 1 },
        fame: 1,
        type: 'main',
    },
    {
        id: 'main_clicks_1k',
        name: 'ダブルクリック',
        description: 'クリック回数が1,000回に到達した。マウスは友達。',
        icon: '🖱️',
        condition: { type: 'clicks', value: 1000 },
        fame: 1,
        type: 'main',
    },
    {
        id: 'main_make_10k',
        name: 'アイスクリーム屋さん',
        description: '累計アイス生産数が1万個に到達。そろそろ店を構えますか？',
        icon: '🏪',
        condition: { type: 'totalIceCreams', value: 10000 },
        fame: 2,
        type: 'main',
    },
    {
        id: 'main_first_upgrade',
        name: '初めての投資',
        description: 'より甘い未来のために、今、投資する。',
        icon: '💡',
        condition: { type: 'upgradesPurchased', value: 1 },
        fame: 2,
        type: 'main',
    },
    {
        id: 'main_buy_cart',
        name: '町の人気者',
        description: 'チリンチリン♪ 軽快なベルの音と共に、街中に幸せを届ける。',
        icon: '🚲',
        condition: { type: 'specificBuildingCount', id: 'icecream_cart', value: 1 },
        fame: 3,
        type: 'main',
    },
    {
        id: 'main_grandpa_10',
        name: 'チームおじいちゃん',
        description: 'おじいちゃんが10人集結。井戸端会議が始まりそうだ。',
        icon: '👨‍👨‍👦‍👦',
        condition: { type: 'specificBuildingCount', id: 'grandpa', value: 10 },
        fame: 3,
        type: 'main',
    },
    {
        id: 'main_click_power_100',
        name: 'パワーアップ！',
        description: 'クリックの力が100に到達。指がディッシャーに見えてきた。',
        icon: '💪',
        condition: { type: 'clickStrength', value: 100 },
        fame: 3,
        type: 'main',
    },
    {
        id: 'main_make_1m',
        name: 'アイスクリーム工場長',
        description: '累計アイス生産数が100万個に到達。ヘルメットがよく似合う。',
        icon: '👷',
        condition: { type: 'totalIceCreams', value: 1000000 },
        fame: 5,
        type: 'main',
    },
    {
        id: 'main_buy_factory',
        name: '大量生産の始まり',
        description: '巨大な製造ラインが24時間稼働。もはやアイスは工業製品。',
        icon: '🏭',
        condition: { type: 'specificBuildingCount', id: 'factory', value: 1 },
        fame: 5,
        type: 'main',
    },
    {
        id: 'main_ips_1m',
        name: '百万馬力',
        description: '秒間アイス生産数（Ips）が100万に到達。もはや川の流れ。',
        icon: '🌊',
        condition: { type: 'ips', value: 1000000 },
        fame: 10,
        type: 'main',
    },
    {
        id: 'main_any_building_100',
        name: '建てすぎ注意',
        description: 'いずれか1種類の施設を100個所有。景観を損なわないように。',
        icon: '🏘️',
        condition: { type: 'anyBuildingCount', value: 100 },
        fame: 10,
        type: 'main',
    },
    {
        id: 'secret_debug',
        name: 'テストプレイ？',
        description: '世界の裏側を覗いてしまったようだな…',
        icon: '🐛',
        condition: { type: 'debug' },
        fame: 5,
        type: 'secret',
    },
];

