const gameSettings = {
    mainClicker: {
        shape: 'circle',
        backgroundColor: '#fecaca',
        image: 'images/icecream_vanilla.png'
    },
    buildings: [
        { id: 'grandpa', name: 'おじいちゃん', icon: 'images/icecream_grandpa.png', description: '全ての始まり。おじいちゃんが作るアイスは、なぜか少し懐かしい味がする。', cost: 15, baseIps: 0.1 },
        { id: 'icecream_disher', name: 'アイスディッシャー', icon: 'images/scoop.png', description: '魔法のディッシャー。置いておくだけで、勝手にアイスをすくい始める。', cost: 75, baseIps: 1 },
        { id: 'icecream_cart', name: 'アイスクリームカート', icon: 'images/icecream_cart.png', description: 'チリンチリン♪ 軽快なベルの音と共に、街中に幸せを届ける移動式店舗。', cost: 850, baseIps: 8 },
        { id: 'stand', name: 'アイススタンド', icon: 'images/icecream_stand.png', description: '街角の一等地。いつも若者たちで賑わっている人気スポット。', cost: 9000, baseIps: 47 },
        { id: 'milk_farm', name: '牛乳牧場', icon: 'images/ranch.png', description: '新鮮なミルクこそ至高のアイスの源。牛たちもアイスが好きらしい。', cost: 100000, baseIps: 260 },
        { id: 'sugar_mine', name: '砂糖鉱山', icon: 'images/sugarmine.png', description: '壁も床も、全てが甘い結晶でできている魅惑の鉱山。', cost: 1200000, baseIps: 1400 },
        { id: 'freezer_truck', name: '冷凍トラック', icon: 'images/truck.png', description: '全国、津々浦々へ。新鮮なアイスを届けるための巨大な輸送網。', cost: 18000000, baseIps: 7800 },
        { id: 'factory', name: 'アイス工場', icon: 'images/factory.png', description: '巨大な製造ラインが24時間稼働。もはやアイスは工業製品。', cost: 300000000, baseIps: 44000 },
        { id: 'tid', name: '東京アイスクリーム大学(TID)', icon: 'images/tidlogo.png', description: 'アイス研究の最高学府。日々、新たな甘さが追求されている。', cost: 4500000000, baseIps: 260000 },
        { id: 'laboratory', name: '研究所', icon: 'images/ice_institute.png', description: '甘くて冷たい錬金術。未知のフレーバーが、ここで生まれる。', cost: 68000000000, baseIps: 1600000 },
        { id: 'mint_forest', name: 'ミントの森', icon: 'images/mintforest.png', description: '爽やかな香りが風に乗って届く。葉の一枚一枚がチョコミント味。', cost: 900000000000, baseIps: 10000000 },
        { id: 'moon_base', name: '月面アイス基地', icon: 'images/mooninstitute.png', description: '静寂の星で、月の光を浴びながら作られる神秘のアイス。', cost: 12000000000000, baseIps: 65000000 },
        { id: 'volcano', name: 'アイスクリーム火山', icon: 'images/icevolcano.png', description: '山頂から流れ出るのは、灼熱の溶岩ではなく、極低温のバニラシェイク。', cost: 150000000000000, baseIps: 430000000 },
        { id: 'dimension', name: 'アイスクリームの次元', icon: 'images/icedimension.png', description: '存在そのものがアイスで構成された異次元。物理法則さえも甘い。', cost: 1800000000000000, baseIps: 2900000000 },
        { id: 'blackhole_freezer', name: 'ブラックホール冷凍庫', icon: 'images/blackhole.png', description: '宇宙のすべてを吸い込む絶対零度の貯蔵庫。アイスの品質は永遠に保たれる。', cost: 23000000000000000, baseIps: 21000000000 },
    ],
    upgrades: [
        { id: 'click1', name: '自動ディッシャー', icon: 'images/autoscoop.png', description: 'クリック性能が4倍になる', cost: 100, effects: { type: 'click', multiplier: 4 } },
        { id: 'click2', name: 'ダブルディッシャー', icon: 'images/doublescoop.png', description: 'クリック性能がさらに4倍になる', cost: 500, prerequisite: 'click1', effects: { type: 'click', multiplier: 4 } },
        { id: 'click3', name: '金のディッシャー', icon: 'images/goldscoop.png', description: 'クリック性能がさらに4倍になる', cost: 10000, prerequisite: 'click2', effects: { type: 'click', multiplier: 4 } },
        { id: 'click4', name: '伝説のディッシャー', icon: 'images/diamondscoop.png', description: 'クリック性能がさらに4倍になる', cost: 100000, prerequisite: 'click3', effects: { type: 'click', multiplier: 4 } },
        { id: 'click5', name: '電動ハンドミキサー', icon: 'images/mixer.png', description: 'クリック性能がさらに4倍になる', cost: 1000000, prerequisite: 'click4', effects: { type: 'click', multiplier: 4 } },
        { id: 'click6', name: '彗星のかけら', icon: 'images/cometfragment.png', description: 'クリック性能がさらに4倍になる', cost: 15000000, prerequisite: 'click5', effects: { type: 'click', multiplier: 4 } },
        { id: 'click7', name: 'ナノマシングローブ', icon: 'images/glove.png', description: 'クリック性能がさらに4倍になる', cost: 200000000, prerequisite: 'click6', effects: { type: 'click', multiplier: 4 } },
        { id: 'click8', name: '氷河期の息吹', icon: 'images/breath.png', description: 'クリック性能がさらに4倍になる', cost: 3000000000, prerequisite: 'click7', effects: { type: 'click', multiplier: 4 } },
        { id: 'click9', name: 'アイデアという名のアイス', icon: 'images/154_20250914143453.png', description: 'クリック性能がさらに2倍になる。ひらめきは甘い。', cost: 50000000000, prerequisite: 'click8', effects: { type: 'click', multiplier: 4 } },
        { id: 'unlock_icecream_disher', name: 'ディッシャーの購入許可', icon: 'images/scoop.png', description: 'アイスディッシャーの販売を開始します。', cost: 70, effects: { type: 'unlock', building: 'icecream_disher' } },
        { id: 'unlock_icecream_cart', name: 'カートの営業許可', icon: 'images/icecream_cart.png', description: 'アイスクリームカートの販売を開始します。', cost: 800, prerequisite: 'unlock_icecream_disher', effects: { type: 'unlock', building: 'icecream_cart' } },
        { id: 'unlock_stand', name: 'スタンドの出店許可', icon: 'images/icecream_stand.png', description: 'アイススタンドの販売を開始します。', cost: 8500, prerequisite: 'unlock_icecream_cart', effects: { type: 'unlock', building: 'stand' } },
        { id: 'unlock_milk_farm', name: '牧場の経営許可', icon: 'images/ranch.png', description: '牛乳牧場の販売を開始します。', cost: 95000, prerequisite: 'unlock_stand', effects: { type: 'unlock', building: 'milk_farm' } },
        { id: 'unlock_sugar_mine', name: '鉱山の採掘許可', icon: 'images/sugarmine.png', description: '砂糖鉱山の販売を開始します。', cost: 1100000, prerequisite: 'unlock_milk_farm', effects: { type: 'unlock', building: 'sugar_mine' } },
        { id: 'unlock_freezer_truck', name: 'トラックの輸送許可', icon: 'images/truck.png', description: '冷凍トラックの販売を開始します。', cost: 17000000, prerequisite: 'unlock_sugar_mine', effects: { type: 'unlock', building: 'freezer_truck' } },
        { id: 'unlock_factory', name: '工場の建設許可', icon: 'images/factory.png', description: 'アイス工場の販売を開始します。', cost: 280000000, prerequisite: 'unlock_freezer_truck', effects: { type: 'unlock', building: 'factory' } },
        { id: 'unlock_tid', name: '大学の開校許可', icon: 'images/tidlogo.png', description: '東京アイスクリーム大学の販売を開始します。', cost: 4200000000, prerequisite: 'unlock_factory', effects: { type: 'unlock', building: 'tid' } },
        { id: 'unlock_laboratory', name: '研究所の設立許可', icon: 'images/ice_institute.png', description: '研究所の販売を開始します。', cost: 65000000000, prerequisite: 'unlock_tid', effects: { type: 'unlock', building: 'laboratory' } },
        { id: 'unlock_mint_forest', name: '森林の探索許可', icon: 'images/mintforest.png', description: 'ミントの森の販売を開始します。', cost: 850000000000, prerequisite: 'unlock_laboratory', effects: { type: 'unlock', building: 'mint_forest' } },
        { id: 'unlock_moon_base', name: '月面基地の建設許可', icon: 'images/mooninstitute.png', description: '月面アイス基地の販売を開始します。', cost: 11000000000000, prerequisite: 'unlock_mint_forest', effects: { type: 'unlock', building: 'moon_base' } },
        { id: 'unlock_volcano', name: '火山の調査許可', icon: 'images/icevolcano.png', description: 'アイスクリーム火山の販売を開始します。', cost: 140000000000000, prerequisite: 'unlock_moon_base', effects: { type: 'unlock', building: 'volcano' } },
        { id: 'unlock_dimension', name: '次元の扉の開放許可', icon: 'images/icedimension.png', description: 'アイスクリームの次元の販売を開始します。', cost: 1700000000000000, prerequisite: 'unlock_volcano', effects: { type: 'unlock', building: 'dimension' } },
        { id: 'unlock_blackhole_freezer', name: 'ブラックホールの利用許可', icon: 'images/blackhole.png', description: 'ブラックホール冷凍庫の販売を開始します。', cost: 22000000000000000, prerequisite: 'unlock_dimension', effects: { type: 'unlock', building: 'blackhole_freezer' } },
    ],
    globalMissionCooldown: 120,
};

